### ISSUE TITLE
find better function names

### ISSUE THREAD

**Issue by vonovak** [vonovak/react-navigation-props-mapper#1]
`withMappedNavigationAndConfigProps` really is a mouthful. Ideas welcome.

**Comment by jimthedev** [comment]
meh, with es6 import aliases it is probably fine unless someone has a ton of Navigators. 

maybe alias them as mapNav and mapNavConfig?

**Comment by everdrone** [comment]
@jimthedev truth is spoken, es6 aliases solved the long naming issues

but maybe `mappedScreen` and `mappedScreenConfig`?
