### ISSUE TITLE
Why it's not devDependency?

### ISSUE THREAD

**Issue by dzienisz** [vonovak/react-navigation-props-mapper#10]
Hey

why this is not devDependency?

`yarn add react-navigation-props-mapper`

**Comment by vonovak** [comment]
hi! I'm not sure I understand - it is not a devDependency because react-navigation-props-mapper is actually used by your app at runtime. Does this make sense? Why do you think it should be a devDependency?

**Comment by dzienisz** [comment]
OK, thank you for explanation :)
