### ISSUE TITLE
Usage with redux compose

### ISSUE THREAD

**Issue by dayhaysoos** [vonovak/react-navigation-props-mapper#15]
I have a connected component I'd like to wrap, I am not sure if I'm doing it the right way, though:

```
export default compose(
    withMappedNavigationParams(),
    connect(mapStateToProps, mapDispatcthToProps),
)(CharacterProfile)
```

I'm trying to use this so I can get props in my navigationProps config, but I'm not seeing the values I'm trying to pass. Am I doing this incorrectly?

Thanks in advanced!

**Comment by vonovak** [comment]
I'm not a redux expert, but you're supposed to use `withMappedNavigationParams()` to wrap the component, not use it with compose.

something like this should work

```js
export default compose(
    connect(mapStateToProps, mapDispatcthToProps),
)(withMappedNavigationParams()(CharacterProfile))
```
