### ISSUE TITLE
Issues with Babel cache

### ISSUE THREAD

**Issue by thewaver** [vonovak/react-navigation-props-mapper#16]
Hi.

Please pardon the ignorance, I am rather green when it comes to environment setup.
I started encountering issues with this package after performing a dependency update.
Namely, it complains that "cache" is not a property of undefined.
The code in question lives inside babel.config.js - it appears that "api" is undefined at this stage.

I am able to run everything if I remove the line
```api.cache(true);```
from the babel.config.js file.

I am using React Native 0.59.5 with yarn 1.17.3. If there are other pertinent packages that you'd like versions for, please let me know.

Thanks in advance!

**Comment by vvscode** [comment]
@vonovak  same for me on the version `1.0.1`

**Comment by vonovak** [comment]
does 1.0.2 fix the issue? All I did is not include the file in the distribution bundle, as it's only intended to be used for compiling the JS with babel

**Comment by vonovak** [comment]
I'm going to assume this was resolved. Thanks!
