### ISSUE TITLE
Can't get params

### ISSUE THREAD

**Issue by creativefull** [vonovak/react-navigation-props-mapper#2]
i have params like this
```js
params : {
balance : 20000
}
```
when i try to console.log(params) its work fine, but when i try console.log(params.balance) i got undefined. what should i do ?

**Comment by vonovak** [comment]
can you provide more code?

**Comment by creativefull** [comment]
its work, the parameter got value. but late delivery
so i just handle with
```js
if (this.props.navigation.params) {
// this is my code
}
```

before thanks :)
