### ISSUE TITLE
Issue with params

### ISSUE THREAD

**Issue by akhlopyk** [vonovak/react-navigation-props-mapper#26]
Hey!
I faced with an issue Cannot read property  'params' of undefined. Looks like something inside this library.

Do you have an idea what might be wrong?
removed modules, reinstalled 4 times react-navigation-props-mapper v2.

Migrated from react-navigation 3.

now - 
react-navigation-props-mapper v2 and react-navigation 5.5.1

Thanks for help!

**Comment by akhlopyk** [comment]
Found solution for my issue.
On start there is no "props.route.params"
os I had to add

"var params=props.route && props.route.params || {};" into dist/index.js

**Comment by vonovak** [comment]
hello, would you mind creating a minimal repro for this? it'd help other people consuming the library, thank you!
