### ISSUE TITLE
TypeError ha

### ISSUE THREAD

**Issue by genglei01** [vonovak/react-navigation-props-mapper#4]
I  install this library and code as the following:

```
import { withMappedNavigationProps } from 'react-navigation-props-mapper'

@withMappedNavigationProps()
export class SomeScreen extends Component {
```

But  I got an error:
![screen shot 2018-03-21 at 2 11 42 pm](https://user-images.githubusercontent.com/3293583/37696490-d9eac084-2d11-11e8-883c-bc17744d1bbb.png)

**Comment by vonovak** [comment]
Maybe you didn't set up babel support for decorators? Can't say for sure
without a runnable reproduction.

**Comment by genglei01** [comment]
I have set up babel.
![image](https://user-images.githubusercontent.com/3293583/37698681-e0bda298-2d1e-11e8-9db4-e486dcd738d3.png)

**Comment by vonovak** [comment]
like I said, I cannot help without having a reproduction, sorry.

**Comment by shashanksinghal** [comment]
Even I am facing this while using with ES6.
Dependencies:

```
"react": "16.3.1",
"react-native": "0.55.3",
"devDependencies": {
    "babel-jest": "22.4.3",
    "babel-plugin-transform-decorators": "^6.24.1",
    "babel-preset-react-native": "4.0.0",
    "eslint-config-google": "^0.9.1",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  }

```

.babelrc file:

> {
>   "presets": ["react-native"],
>   "plugins": ["transform-decorators"]
> }
