### ISSUE TITLE
Props mapper breaks when upgrading from 0.1.3 => 0.2.0

### ISSUE THREAD

**Issue by brianlovin** [vonovak/react-navigation-props-mapper#5]
Hey @vonovak - we're really loving this lib for our project at https://github.com/withspectrum/spectrum.

Today I was upgrading some deps and found that upgrading from `0.1.3` to `0.2.0` breaks our app. Here's an example of how we're using this with a stack:

```js
import Thread from '../Thread';
import { withMappedNavigationProps } from 'react-navigation-props-mapper';
import type { NavigationScreenConfigProps } from 'react-navigation';

const BaseStack = {
  Thread: {
    screen: withMappedNavigationProps(Thread),
    navigationOptions: ({ navigation }: NavigationScreenConfigProps) => ({
      headerTitle: navigation.state.params.title || 'Thread',
      tabBarVisible: false,
    }),
  }
};

export default BaseStack;
```

When I upgrade to `0.2.0` I get this error when navigating to a `Thread`:
![screenshot 2018-05-25 13 07 27](https://user-images.githubusercontent.com/1923260/40564200-a5066c4a-601c-11e8-991e-f152304d2e9c.png)

If I change the stack to:

```js
Thread: {
    screen: Thread,
    navigationOptions: ({ navigation }: NavigationScreenConfigProps) => ({
      headerTitle: navigation.state.params.title || 'Thread',
      tabBarVisible: false,
    }),
  }
```

the view loads, but without the mapped props.

Here are the rest of our deps if it helps:
```
"dependencies": {
    "expo": "^26.0.0",
    "metro-bundler": "^0.22.1",
    "react": "16.3.0-alpha.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz",
    "react-navigation": "^2.0.2",
    "react-navigation-props-mapper": "^0.2.0",
  },
  "devDependencies": {
    "cross-env": "^5.1.1",
    "detox": "^6.0.0",
    "detox-expo-helpers": "^0.2.0",
    "exp": "^52.0.0",
    "jest": "^22.0.3",
    "jest-expo": "^26.0.0",
    "react-test-renderer": "^16.2.0"
  },
```

In the meantime I'm happy to sit tight on `0.1.3`, just wanted to give you a heads up :)

**Comment by vonovak** [comment]
Hi! I'm sorry for this! I haven't followed semantic release with the 0.2 version. The change you need to do is best seen in this commit https://github.com/vonovak/react-navigation-props-mapper/commit/0168211774c63d1d1925b50434e175b16b168473 where I actually removed the note of the breaking change.

I hope this helps.

**Comment by brianlovin** [comment]
@vonovak I see, thanks for the context here! I'll try and upgrade later with the new syntax :)
