### ISSUE TITLE
Some important data is removed from navigation object

### ISSUE THREAD

**Issue by amitpdev** [vonovak/react-navigation-props-mapper#8]
I noticed some of the data originally provided in this.props.navigation is not passed
when using withMappedNavigationProps.
i.e:
routeName

For me, it made this library useless as I need the route name to do some flow calculations in my app.

**Comment by vonovak** [comment]
Afaik there is no code in this lib that would remove data from the navigation prop. Can you please provide a runnable repro of this issue? Thank you!

**Comment by vonovak** [comment]
closing since there is no repro. To the best of my knowledge, this package does not remove anything from the props.
